name: Angular Package

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 14
      - run: npm ci
      - run: npm run build
      - name: Upload math result for job 1
        uses: actions/upload-artifact@v3
        with:
          name: homework
          path: dist


  publish-gpr:
    needs: build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: /home/runner/work/carousel/carousel/dist/carousel
    permissions:
      packages: write
      contents: read
    steps:
      - name: Download math result for job 2
        uses: actions/download-artifact@v3
        with:
          name: homework
      - run: ls -ls
      - uses: actions/setup-node@v3
        with:
          registry-url: https://npm.pkg.github.com/
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
